
import { Suspense } from 'react'
import Providers from './Providers'
import './globals.css'
import 'bootstrap-icons/font/bootstrap-icons.css'
import Loading from './result/Loading'


export const metadata = {
  title: 'Website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className='dark:bg-[#212529]'><Providers>{children}</Providers></body>
    </html>
  )
}
